# Generated by Django 3.2.3 on 2021-06-03 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidades',
            old_name='habiidad',
            new_name='habilidad',
        ),
    ]
