# Generated by Django 3.2.3 on 2021-06-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_rename_habiidad_habilidades_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
